# ⚠️  En producción usa Sealed Secrets o External Secrets Operator.
# Valores codificados en base64:  echo -n "valor" | base64
#
#   students_user  → c3R1ZGVudHNfdXNlcg==
#   students_pass  → c3R1ZGVudHNfcGFzcw==
#   root_pass      → cm9vdF9wYXNz
#   students_db    → c3R1ZGVudHNfZGI=
#   admin          → YWRtaW4=
#   admin_pass     → YWRtaW5fcGFzcw==
#   students-service-super-secret-key-minimum-32-chars! → c3R1ZGVudHMtc2VydmljZS1zdXBlci1zZWNyZXQta2V5LW1pbmltdW0tMzItY2hhcnMh

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: students
type: Opaque
data:
  root-password:  cm9vdF9wYXNz          # root_pass
  database:       c3R1ZGVudHNfZGI=      # students_db
  username:       c3R1ZGVudHNfdXNlcg==  # students_user
  password:       c3R1ZGVudHNfcGFzcw==  # students_pass

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: students
type: Opaque
data:
  username: YWRtaW4=        # admin
  password: YWRtaW5fcGFzcw== # admin_pass

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: students
type: Opaque
data:
  # students-service-super-secret-key-minimum-32-chars!
  secret-key: c3R1ZGVudHMtc2VydmljZS1zdXBlci1zZWNyZXQta2V5LW1pbmltdW0tMzItY2hhcnMh
