apiVersion: v1
kind: ConfigMap
metadata:
  name: academy-config
  namespace: academy
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  MongoDB__DatabaseName: "academy_read"
  ASPNETCORE_URLS: "http://+:8080"
